//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_BD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountStatement> AccountStatement { get; set; }
        public virtual DbSet<Benefactor> Benefactor { get; set; }
        public virtual DbSet<Coin> Coin { get; set; }
        public virtual DbSet<Mov_CO> Mov_CO { get; set; }
        public virtual DbSet<Mov_CO_Interest> Mov_CO_Interest { get; set; }
        public virtual DbSet<Movement_CA> Movement_CA { get; set; }
        public virtual DbSet<ObjetiveAccount> ObjetiveAccount { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Relationship> Relationship { get; set; }
        public virtual DbSet<SavingsAccount> SavingsAccount { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeDocIdentity> TypeDocIdentity { get; set; }
        public virtual DbSet<TypeMovCO> TypeMovCO { get; set; }
        public virtual DbSet<TypeMovCOInt> TypeMovCOInt { get; set; }
        public virtual DbSet<TypeMovement_CA> TypeMovement_CA { get; set; }
        public virtual DbSet<TypeSavingsAccount> TypeSavingsAccount { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserCanAccess> UserCanAccess { get; set; }
    }
}
