//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mov_CO_Interest
    {
        public int Id { get; set; }
        public int TypeMovCOinterestId { get; set; }
        public int ObjectiveAccountId { get; set; }
        public System.DateTime DateOfMovCOinterest { get; set; }
        public decimal Fee { get; set; }
        public double NewAcumInterest { get; set; }
    
        public virtual ObjetiveAccount ObjetiveAccount { get; set; }
        public virtual TypeMovCOInt TypeMovCOInt { get; set; }
    }
}
