//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement_CA
    {
        public int Id { get; set; }
        public int SavingsAccountId { get; set; }
        public int TypeMovId { get; set; }
        public int AccountStatementId { get; set; }
        public decimal Amount { get; set; }
        public decimal NewBalance { get; set; }
        public string Description { get; set; }
        public bool Visible { get; set; }
        public System.DateTime DateOfMov { get; set; }
    
        public virtual AccountStatement AccountStatement { get; set; }
        public virtual SavingsAccount SavingsAccount { get; set; }
        public virtual TypeMovement_CA TypeMovement_CA { get; set; }
    }
}
