//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetiveAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjetiveAccount()
        {
            this.Mov_CO = new HashSet<Mov_CO>();
            this.Mov_CO_Interest = new HashSet<Mov_CO_Interest>();
        }
    
        public int Id { get; set; }
        public int SavingsAccountId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Fee { get; set; }
        public string Objective { get; set; }
        public decimal Balance { get; set; }
        public double AcumInterest { get; set; }
        public string DaysOfDeposit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mov_CO> Mov_CO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mov_CO_Interest> Mov_CO_Interest { get; set; }
        public virtual SavingsAccount SavingsAccount { get; set; }
    }
}
