//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeSavingsAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeSavingsAccount()
        {
            this.SavingsAccounts = new HashSet<SavingsAccount>();
        }
    
        public int Id { get; set; }
        public int CoinId { get; set; }
        public string Name { get; set; }
        public double InterestRate { get; set; }
        public decimal PenaltyForBreach { get; set; }
        public decimal MinimunBalance { get; set; }
        public decimal MensualAccountForService { get; set; }
        public int MaxOpsHuman { get; set; }
        public int MaxOpsAtm { get; set; }
        public double ExceedComisionHumanMont { get; set; }
        public double ExceedComisionAtmMont { get; set; }
    
        public virtual Coin Coin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavingsAccount> SavingsAccounts { get; set; }
    }
}
